# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Mar  9 19:00:24 2019
# ------------------------------------------------

package:
    name: gnutls
    version: 3.6.5
source:
    fn: gnutls-3.6.5.tar.xz
    patches:
        - 0002-pkgconfig.patch
        - 0003-Fix-libcrypto-test-it-must-always-fail.patch
    sha256: 073eced3acef49a3883e69ffd5f0f0b5f46e2760ad86eddc6c0866df4e7abb35
    url: ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/gnutls-3.6.5.tar.xz
build:
    ignore_run_exports:
        - gmp
        - libgcc-ng
    number: '1002'
    run_exports:
        - gnutls >=3.6.5,<3.7.0a0
    string: hd3a4fd2_1002
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h14c3975_1002
        - pkg-config 0.29.2 h14c3975_1004
    host:
        - gmp 6.1.2 hf484d3e_1000
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - nettle 3.4.1 h1bed415_1002
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - nettle >=3.4.1
        - nettle >=3.4.1,<3.5.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libgnutls${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libgnutlsxx${SHLIB_EXT}
about:
    dev_url: https://gitlab.com/gnutls/gnutls/tree/master
    doc_url: http://www.gnutls.org/documentation.html
    home: http://www.gnutls.org/index.html
    license: LGPLv2.1
    license_family: LGPL
    license_file: LICENSE
    summary: GnuTLS is a secure communications library implementing the SSL, TLS and
        DTLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - sachalau
        - scopatz
        - sdvillal
