# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 16 12:52:30 2019
# ------------------------------------------------

package:
    name: certifi
    version: 2019.6.16
source:
    -   folder: certifi
        sha256: 945e3ba63a0b9f577b1395204e13c3a231f9bc0223888be653286534e5873695
        url: https://pypi.io/packages/source/c/certifi/certifi-2019.6.16.tar.gz
    -   folder: pip_wheel
        sha256: 993134f0475471b91452ca029d4390dc8f298ac63a712814f101cd1b6db46676
        url: https://pypi.io/packages/py2.py3/p/pip/pip-19.1.1-py2.py3-none-any.whl
    -   folder: setuptools_wheel
        sha256: c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf
        url: https://pypi.io/packages/py2.py3/s/setuptools/setuptools-41.0.1-py2.py3-none-any.whl
build:
    number: '1'
    string: py37_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: certifi/LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
