# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: numpy-base
    version: 1.18.1
source:
    -   patches:
            - 0001-intel_mkl-version.patch
            - 0003-intel_init_mkl.patch
            - 0007-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
        sha256: b6ff59cee96b454516e47e7721098e6ceebef435e3e21ac2d6c3b8b02628eb77
        url: https://pypi.io/packages/source/n/numpy/numpy-1.18.1.zip
build:
    force_use_keys:
        - python
    noarch: false
    number: '1'
    script: install_base.sh
    string: py36hde5b4d6_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py36_0
        - cython 0.29.14 py36he6710b0_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.6.10 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 44.0.0 py36_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas 1.0 mkl
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - test -e $SP_DIR/numpy/distutils/site.cfg
about:
    description: 'NumPy is the fundamental package needed for scientific computing
        with Python.

        '
    dev_source_url: https://github.com/numpy/numpy/tree/master/doc
    dev_url: https://github.com/numpy/numpy
    doc_url: https://docs.scipy.org/doc/numpy-1.18.1/reference/
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
