# This file created by conda-build 3.18.5
# meta.yaml template originally from:
# /io/tensorflow_recipes/tensorflow-base-gpu, last modified Tue Jun 25 21:13:43 2019
# ------------------------------------------------

package:
    name: tensorflow-base
    version: 1.14.0
source:
    fn: tensorflow-1.14.0.tar.gz
    patches:
        - 0008-do-not-include-B-usr-bin-flag.patch
        - 0009-patch-nccl-for-older-kernels.patch
    sha256: aa2a6a1daafa3af66807cfe0bc77bfe1144a9a53df9a96bab52e3e575b3047ed
    url: https://github.com/tensorflow/tensorflow/archive/v1.14.0.tar.gz
build:
    entry_points:
        - freeze_graph = tensorflow.python.tools.freeze_graph:run_main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    number: '0'
    string: gpu_py37he45bfe2_0
requirements:
    build:
        - bazel 0.24.1 he6710b0_0
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 5.4.0 had2808c_24
        - gcc_impl_linux-64 5.4.0 habb00fd_3
        - gcc_linux-64 5.4.0 h98af8de_24
        - gxx_impl_linux-64 5.4.0 hdf63c60_3
        - gxx_linux-64 5.4.0 h98af8de_24
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - openjdk 8.0.152 h46b5887_1
    host:
        - absl-py 0.7.1 py37_0
        - astor 0.7.1 py37_0
        - blas 1.0 openblas
        - c-ares 1.15.0 h7b6447c_1
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py37_0
        - cudatoolkit 10.1.168 0
        - cudnn 7.6.0 cuda10.1_0
        - cupti 10.1.168 0
        - gast 0.2.2 py37_0
        - google-pasta 0.1.7 py_0
        - grpcio 1.16.1 py37hf8bcb03_1
        - h5py 2.9.0 py37h7918eee_0
        - hdf5 1.10.4 hb1b8bf9_0
        - joblib 0.13.2 py37_0
        - keras-applications 1.0.8 py_0
        - keras-preprocessing 1.1.0 py_1
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libopenblas 0.3.6 h5a2b251_0
        - libprotobuf 3.8.0 hd408876_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - numpy 1.14.6 py37hec00662_4
        - numpy-base 1.14.6 py37h2f8d375_4
        - openssl 1.1.1c h7b6447c_1
        - pcre 8.43 he6710b0_0
        - pip 19.1.1 py37_0
        - portpicker 1.3.1 py37_0
        - protobuf 3.8.0 py37he6710b0_0
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - scikit-learn 0.21.2 py37h22eb022_0
        - scipy 1.2.1 py37he2b7bc3_0
        - setuptools 39.1.0 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.28.0 h7b6447c_0
        - swig 3.0.12 h38cdd7d_3
        - termcolor 1.1.0 py37_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.4 py37_0
        - wrapt 1.11.1 py37h7b6447c_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - absl-py >=0.7.0
        - astor >=0.6.0
        - cudatoolkit >=10.1.168,<10.2.0a0
        - cudnn >=7.6.0,<8.0a0
        - cupti
        - gast >=0.2.0
        - google-pasta >=0.1.6
        - grpcio >=1.8.6
        - keras-applications >=1.0.6
        - keras-preprocessing >=1.0.5
        - libgcc-ng >=5.4.0
        - libstdcxx-ng >=5.4.0
        - numpy >=1.14.6,<2.0a0
        - protobuf >=3.6.1
        - python >=3.7,<3.8.0a0
        - six >=1.10.0
        - termcolor >=1.1.0
        - wrapt >=1.11.1
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - freeze_graph --help
        - saved_model_cli --help
        - tflite_convert --help
        - toco_from_protos --help
        - toco --help
    files:
        - gpu_test.py
about:
    description: 'TensorFlow provides multiple APIs.The lowest level API, TensorFlow
        Core

        provides you with complete programming control.

        Base GPU package contains only tensorflow, not tensorflow-tensorboard.

        '
    dev_url: https://github.com/tensorflow/tensorflow
    doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
    doc_url: https://www.tensorflow.org/get_started/get_started
    home: http://tensorflow.org/
    license: Apache 2.0
    license_family: Apache
    summary: TensorFlow is a machine learning library, base GPU package, tensorflow
        only.
extra:
    copy_test_source_files: true
    final: true
    tflow_variant: gpu
