# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Dec 22 22:39:22 2018
# ------------------------------------------------

package:
    name: graphite2
    version: 1.3.13
source:
    sha256: dd63e169b0d3cf954b397c122551ab9343e0696fb2045e1b326db0202d875f06
    url: https://github.com/silnrsi/graphite/releases/download/1.3.13/graphite2-1.3.13.tgz
build:
    detect_binary_files_with_prefix: true
    number: '1000'
    string: hf484d3e_1000
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2018.10.15 ha4d7672_0
        - cmake 3.13.1 h8d4ced6_1000
        - curl 7.63.0 h646f8bb_1000
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - krb5 1.16.2 hc83ff2d_1000
        - libcurl 7.63.0 h01ee5af_1000
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 7.3.0 hdf63c60_0
        - libssh2 1.8.0 h1ad7b7a_1003
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libuv 1.24.1 h14c3975_1000
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.0.2p h14c3975_1001
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 h84994c4_1000
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1003
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://graphite.sil.org/
    license: LGPLv2
    license_file: COPYING
    summary: A "smart font" system that handles the complexities of lesser-known languages
        of the world.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
